/* ===== Circuits.com — Supabase-backed data store =====
   Real persistence shared across all clients and devices.
   Requires the Supabase JS client (loaded from CDN) before this file.
   The URL and publishable key below are PUBLIC by design (safe to embed);
   all access is enforced server-side by Row Level Security. */

const SUPABASE_URL = 'https://ghpruernzhjwsgsezdyn.supabase.co';
const SUPABASE_KEY = 'sb_publishable_zmOQinynNkuWdHUeHrFdDA_y6UnLyL4';

const sb = (window.supabase && window.supabase.createClient)
  ? window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY)
  : null;

/* ---- pricing ----
   Beta rates. Original owners keep these for as long as their subscription
   stays active, so these numbers are a floor we honour, not a list price.
   Yearly works out to ten months, i.e. two months free. */
const BASE_FEE = 99, BANNER_FEE = 399, BADGE_FEE = 49;
const BASE_FEE_YEAR = 999, BANNER_FEE_YEAR = 3999, BADGE_FEE_YEAR = 399;
function effPrice(v, fallback){
  return (v==null || v==='' || isNaN(Number(v))) ? fallback : Number(v);
}
function appPrice(a){
  let p = effPrice(a && a.listing_price, BASE_FEE);
  if(a && a.banner) p += effPrice(a.banner_price, BANNER_FEE);
  if(a && a.badge)  p += effPrice(a.badge_price, BADGE_FEE);
  return p;
}
function appPriceLabel(a){ return (a && a.fee) ? a.fee : ('$' + appPrice(a) + '/mo'); }

/* ---- read ---- */
async function fetchApplications(){
  if(!sb) return [];
  // oldest first — new listings join at the BOTTOM of the list
  // (earlier claims keep the higher permanent position)
  // secondary sort by id keeps rows from jumping when timestamps tie
  const { data, error } = await sb.from('applications').select('*')
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.error('fetchApplications', error); return []; }
  return data || [];
}
async function fetchApproved(){
  if(!sb) return [];
  const { data, error } = await sb.from('applications').select('*').eq('status','Approved')
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.error('fetchApproved', error); return []; }
  return data || [];
}
/* ===== Keyword matching ruleset =====
   1. Lowercase everything.
   2. Strip every non-letter/digit (hyphens, spaces, punctuation) — "semi-conductors" == "semi conductors" == "semiconductors".
   3. Singularize the plural tail — "sensors" == "sensor", "switches" == "switch", "batteries" == "battery".
   4. EXACT match only after normalization. No substring/partial matching, so
      "list test 2" never matches "list test 3" and "zzz" only matches "zzz".
   5. Blank/empty keywords never match anything. */
function singularize(n){
  if(n.length>4 && n.endsWith('ies')) return n.slice(0,-3)+'y';   // batteries -> battery
  if(n.length>3 && /(?:x|z|ch|sh)es$/.test(n)) return n.slice(0,-2); // switches -> switch, boxes -> box
  if(n.length>3 && n.endsWith('s') && !n.endsWith('ss')) return n.slice(0,-1); // sensors -> sensor, fuses -> fuse
  return n;
}
function normKw(s){
  return singularize((s||'').toLowerCase().replace(/[^a-z0-9]/g,''));
}
/* Approval-level cleanup for stored keywords: lowercase, no hyphens, no plurals. */
function cleanKw(s){
  let v = (s||'').toLowerCase().replace(/-+/g,' ').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();
  return v.replace(/([a-z0-9]+)$/, w => singularize(w));
}
/* One live listing per company for a searched keyword (skips paused ones).
   Postgres does the matching on an index over applications.keyword_norm, which
   is generated by norm_kw() — the SQL twin of normKw() above. This used to pull
   every approved listing into the browser and filter here, so search got slower
   with every listing sold. Still oldest-first: earlier claims keep the higher
   permanent position. */
async function fetchApprovedByKeyword(keyword){
  if(!sb) return [];
  const k = normKw(keyword);
  if(!k) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('status','Approved').eq('paused', false).eq('keyword_norm', k)
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  /* Throw, don't return []. An empty array here means "nobody owns this
     keyword", which the results page turns into a pitch to buy it. If the
     request merely failed we would be offering a keyword somebody already
     owns — and could sell it twice. Callers must tell the two apart. */
  if(error){ console.error('fetchApprovedByKeyword', error); throw error; }
  const seen = new Set(), out = [];
  for(const a of (data || [])){ if(seen.has(a.company)) continue; seen.add(a.company); out.push(a); }
  return out;
}

/* ---- what people look for ----
   Logged for every search, found or not. Deliberately anonymous: the term, the
   number of hits and the time, nothing that ties it to a person. The value is
   the aggregate — which keywords are wanted and which ones we cannot answer.

   Never awaited and never surfaced: a failure to log must not slow a search
   down or show the searcher an error about our own bookkeeping. */
function logSearch(term, hits){
  if(!sb) return;
  const q = (term || '').trim().slice(0, 120);
  if(!q) return;
  try{
    sb.from('searches').insert({ q, q_norm: normKw(q).slice(0, 120), hits: hits | 0 })
      .then(({ error }) => { if(error) console.warn('logSearch', error.message); });
  }catch(err){ console.warn('logSearch failed', err); }
}

/* A buyer who found nothing, asking to be told when somebody lists. This one
   the caller DOES wait on, because they are owed an answer. */
async function registerWanted(keyword, email, note){
  if(!sb) return 'No connection';
  const { error } = await sb.from('wanted').insert({
    keyword: (keyword || '').trim().slice(0, 120),
    email: (email || '').trim().slice(0, 320),
    note: (note || '').trim().slice(0, 1000) || null
  });
  if(error){ console.error('registerWanted', error); return error.message; }
  return '';
}

/* Related listings when the exact keyword has none: split what they typed and
   look for a listing on any single word of it, so "crystal oscillator" reaches
   the company listed under "oscillators". Clearly labelled as related in the
   page — an exact keyword is what companies pay for and must not be diluted. */
async function fetchRelatedByKeyword(keyword){
  if(!sb) return [];
  const words = (keyword || '').toLowerCase().split(/[^a-z0-9]+/).filter(w => w.length > 2);
  const terms = [...new Set(words.map(normKw))].filter(Boolean).slice(0, 6);
  if(!terms.length) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('status','Approved').eq('paused', false).in('keyword_norm', terms)
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.warn('fetchRelatedByKeyword', error.message); return []; }
  const seen = new Set(), out = [];
  for(const a of (data || [])){ if(seen.has(a.company)) continue; seen.add(a.company); out.push(a); }
  return out;
}

/* ---- company logo storage (Supabase Storage, public bucket "logos") ---- */
async function uploadLogo(file){
  if(!sb || !file) return '';
  const ext = (file.name.split('.').pop() || 'png').toLowerCase().replace(/[^a-z0-9]/g,'');
  const path = Date.now() + '-' + Math.random().toString(36).slice(2,8) + '.' + ext;
  const { error } = await sb.storage.from('logos').upload(path, file, { contentType: file.type, cacheControl: '31536000' });
  if(error){ console.error('uploadLogo', error); return ''; }
  return sb.storage.from('logos').getPublicUrl(path).data.publicUrl;
}
function isLogoUrl(s){ return /^https?:\/\//i.test(s||''); }

/* ---- listing documentation storage (Supabase Storage, public bucket "docs") ---- */
async function uploadDoc(file){
  if(!sb || !file) return null;
  const ext = (file.name.split('.').pop() || 'pdf').toLowerCase().replace(/[^a-z0-9]/g,'');
  const path = Date.now() + '-' + Math.random().toString(36).slice(2,8) + '.' + ext;
  const { error } = await sb.storage.from('docs').upload(path, file, { contentType: file.type, cacheControl: '31536000' });
  if(error){ console.error('uploadDoc', error); return null; }
  return { name: file.name, url: sb.storage.from('docs').getPublicUrl(path).data.publicUrl };
}

/* ---- write ---- */
/* Join form: one submission becomes one row per keyword. */
async function addApplicationKeywords(base, keywords){
  if(!sb) throw new Error('No connection');
  const list = (keywords && keywords.length) ? keywords.map(cleanKw) : [''];
  const rows = list.map(kw => Object.assign({}, base, {
    keyword: kw, keywords: kw ? [kw] : [], status: base.status || 'Pending'
  }));
  const { error } = await sb.from('applications').insert(rows);
  if(error){ console.error('addApplicationKeywords', error); throw error; }
  return rows;
}
async function updateAppStatus(id, status){
  if(!sb) return null;
  const { error } = await sb.from('applications').update({ status }).eq('id', id);
  if(error) console.error('updateAppStatus', error);
  return error || null;
}
/* Approve every keyword row for a company (Add Listing dropdown). */
async function approveCompany(company){
  if(!sb) return;
  const { error } = await sb.from('applications').update({ status:'Approved', paused:false }).eq('company', company);
  if(error) console.error('approveCompany', error);
}
async function setPaused(id, paused){
  if(!sb) return null;
  const { error } = await sb.from('applications').update({ paused }).eq('id', id);
  if(error) console.error('setPaused', error);
  return error || null;
}
async function updateApplication(id, fields){
  if(!sb) return null;
  if('keyword' in fields){ fields.keyword = cleanKw(fields.keyword); fields.keywords = fields.keyword ? [fields.keyword] : []; }
  const { error } = await sb.from('applications').update(fields).eq('id', id);
  if(error) console.error('updateApplication', error);
  return error || null;
}
async function deleteApplication(id){
  if(!sb) return;
  const { error } = await sb.from('applications').delete().eq('id', id);
  if(error) console.error('deleteApplication', error);
}

/* ---- auth (staff) ---- */
async function currentUser(){ if(!sb) return null; const { data } = await sb.auth.getUser(); return data ? data.user : null; }
async function checkStaff(){ if(!sb) return false; const { data, error } = await sb.rpc('is_staff'); if(error){ console.error('is_staff', error); return false; } return !!data; }
/* Sign in with an email OR a Circuits.com username. Supabase only knows
   emails, so a username is resolved first. A failed lookup still calls
   signInWithPassword so a wrong username and a wrong password come back
   with the same error, rather than confirming which usernames exist. */
async function signIn(identifier, password){
  let email = (identifier || '').trim();
  if(email && !email.includes('@')){
    try{
      const { data } = await sb.rpc('email_for_login', { p_id: email });
      if(data) email = data;
    }catch(e){ console.warn('username lookup failed', e); }
  }
  return sb.auth.signInWithPassword({ email, password });
}
async function signUp(email, password){ return sb.auth.signUp({ email, password }); }

/* ---- password reset ----
   Accepts an email OR a username, the same as signing in. Always reports
   success: telling someone "no account with that email" turns this form into
   a way to discover who is registered. */
async function requestPasswordReset(identifier){
  if(!sb) return 'No connection';
  let email = (identifier || '').trim();
  if(email && !email.includes('@')){
    try{
      const { data } = await sb.rpc('email_for_login', { p_id: email });
      if(data) email = data;
    }catch(e){ console.warn('username lookup failed', e); }
  }
  if(email.includes('@')){
    const { error } = await sb.auth.resetPasswordForEmail(email, {
      redirectTo: location.origin + '/reset'
    });
    if(error){
      console.warn('resetPasswordForEmail', error.message);
      /* Whether the send FAILED is not a secret — it says nothing about who is
         registered — and swallowing it is worse than useless: the visitor is
         told to check an inbox that will never receive anything. The account's
         existence stays hidden; the outage does not. */
      const status = error.status || error.code;
      if(status === 429 || /rate limit/i.test(error.message || '')){
        /* Two different limits arrive as 429: a short per-address wait after a
           request that DID send, and the project-wide hourly cap. Telling
           someone to wait an hour when it is really 45 seconds sends them away
           for no reason, so use the wait the server actually reports. */
        const secs = (/after (\d+) seconds?/i.exec(error.message || '') || [])[1];
        if(secs){
          return 'A reset link was just sent. If it has not arrived, you can ask for another in '
               + secs + ' seconds.';
        }
        return 'Too many reset emails have been sent from Circuits.com in the last hour. '
             + 'Please try again shortly, or email support@circuits.com and we will reset it for you.';
      }
      return 'We could not send the reset email just now. Please try again in a few minutes, '
           + 'or email support@circuits.com.';
    }
  }
  return '';
}
/* Called on /reset. Supabase puts a recovery session in the URL, which the
   client picks up on load, so this is just a password change. */
async function setNewPassword(password){
  if(!sb) return 'No connection';
  const { error } = await sb.auth.updateUser({ password });
  return error ? error.message : '';
}
async function signOut(){ if(sb) await sb.auth.signOut(); }
/* Ends every session on every device, not just this browser. What you want
   after a shared laptop or a lost phone. */
async function signOutEverywhere(){
  if(!sb) return 'Not connected.';
  const { error } = await sb.auth.signOut({ scope: 'global' });
  if(error){ console.error('signOutEverywhere', error); return error.message; }
  return '';
}
/* Returns 'deleted', or 'still_owns_listing' when the account manages a paid
   listing — see delete_own_account() for why that case is refused. */
async function deleteOwnAccount(){
  if(!sb) return 'error';
  const { data, error } = await sb.rpc('delete_own_account');
  if(error){ console.error('delete_own_account', error); return 'error'; }
  return data;
} async function loadPrefs(page){ if(!sb) return null; const { data, error } = await sb.from('admin_prefs').select('prefs').eq('page', page).maybeSingle(); if(error){ console.error('loadPrefs', error); return null; } return data ? data.prefs : null; } async function savePrefs(page, prefs){ if(!sb) return; const { data } = await sb.auth.getUser(); if(!data || !data.user) return; const { error } = await sb.from('admin_prefs').upsert({ user_id: data.user.id, page, prefs, updated_at: new Date().toISOString() }, { onConflict: 'page' }); if(error) console.error('savePrefs', error); }

/* ===================================================================
   Company profiles
   =================================================================== */

/* Must stay identical to the SQL slugify() in the database. */
function slugify(s){
  return (s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
}
/* A company's public address is its handle, straight off the root:
   circuits.com/zzzelec — short enough to put on an advert. */
function profileUrl(handle){
  return handle ? '/' + handle : '';
}
/* Must match handle_ok() in the database. */
function handleFormatOk(h){
  return /^[a-z0-9]([a-z0-9_-]*[a-z0-9])?$/.test(h||'')
      && h.length >= 3 && h.length <= 32
      && !/--|__|_-|-_/.test(h);
}
/* Is this handle free? Returns '' if available, or the reason it is not.
   circuits.com/<name> is one namespace shared by listings and profiles, so the
   database answers this — the same function the insert triggers use. */
const HANDLE_WHY = {
  format:   '3–32 characters: letters, numbers, and single hyphens or underscores between them.',
  reserved: 'That name is reserved by Circuits.com.',
  company:  'Taken by a company listing.',
  profile:  'Taken by another profile.'
};
async function handleAvailable(handle, ownSlug, ownUser){
  const h = (handle||'').toLowerCase().trim();
  if(!handleFormatOk(h)) return HANDLE_WHY.format;
  if(!sb) return 'No connection';
  const { data, error } = await sb.rpc('handle_taken',
    { p_handle: h, p_user: ownUser || null, p_slug: ownSlug || null });
  if(error){ console.error('handle_taken', error); return 'Could not check that name right now.'; }
  return HANDLE_WHY[data] || '';
}

/* Is a real account behind this listing? Drives the Unclaimed badge. */
async function companyClaimed(slug){
  if(!sb || !slug) return true;   // fail closed: never label a listing unclaimed by mistake
  const { data, error } = await sb.rpc('company_claimed', { p_slug: slug });
  if(error){ console.error('company_claimed', error); return true; }
  return !!data;
}

/* A profile run by a Circuits.com admin carries our own mark. Fail closed the
   other way round from companyClaimed: if we cannot tell, do not award the
   badge — wrongly claiming a listing is ours is worse than missing one. */
async function companyRunByStaff(slug){
  if(!sb || !slug) return false;
  const { data, error } = await sb.rpc('company_run_by_staff', { p_slug: slug });
  if(error){ console.error('company_run_by_staff', error); return false; }
  return !!data;
}

/* ---- profiles: a person, separate from any company listing ---- */
async function fetchProfileByHandle(handle){
  if(!sb || !handle) return null;
  const { data, error } = await sb.from('profiles').select('*')
    .ilike('handle', (handle||'').trim()).maybeSingle();
  // same reasoning as fetchCompanyByHandle: never invent a free address
  if(error){ console.error('fetchProfileByHandle', error); throw error; }
  return data;
}
async function myProfile(){
  if(!sb) return null;
  const { data, error } = await sb.rpc('my_profile');
  if(error){ console.error('my_profile', error); return null; }
  return (data && data[0]) || null;
}
async function updateMyProfile(fields){
  if(!sb) return 'No connection';
  const u = await currentUser();
  if(!u) return 'Not signed in';
  const { data, error } = await sb.from('profiles').update(fields).eq('user_id', u.id).select();
  if(error) return error.message;
  if(!data || !data.length) return 'That change was refused.';
  return '';
}
/* Register: the account and the circuits.com address are created together.
   The handle rides along as signup metadata because email confirmation means
   there is no session yet — a trigger turns it into the profile row, so the
   address is held from the moment the account exists. */
async function registerProfile(email, password, handle, displayName){
  if(!sb) return 'No connection';
  const { error } = await sb.auth.signUp({
    email, password,
    options: { data: { handle: (handle||'').toLowerCase().trim(), display_name: displayName || '' } }
  });
  return error ? error.message : '';
}

/* ---- public reads ---- */
async function fetchCompany(slug){
  if(!sb || !slug) return null;
  const { data, error } = await sb.from('companies').select('*').eq('slug', slug).maybeSingle();
  if(error){ console.error('fetchCompany', error); return null; }
  return data;
}
/* Public pages address a company by its handle, not its internal slug. */
async function fetchCompanyByHandle(handle){
  if(!sb || !handle) return null;
  const { data, error } = await sb.from('companies')
    .select('*').eq('handle', (handle||'').toLowerCase()).maybeSingle();
  // null means "this address is free"; a failed lookup must not claim that
  if(error){ console.error('fetchCompanyByHandle', error); throw error; }
  return data;
}
/* Live keywords for a company, in the permanent order they were claimed. */
async function fetchCompanyKeywords(slug){
  if(!sb || !slug) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('company_slug', slug).eq('status','Approved')
    .order('created_at', { ascending:true });
  if(error){ console.error('fetchCompanyKeywords', error); return []; }
  return (data||[]).filter(r => !r.paused && r.keyword);
}
async function fetchReviews(slug){
  if(!sb || !slug) return [];
  const { data, error } = await sb.from('reviews').select('*')
    .eq('company_slug', slug).eq('status','Approved')
    .order('created_at', { ascending:false });
  if(error){ console.error('fetchReviews', error); return []; }
  return data || [];
}
/* ---- public writes ---- */
async function submitReview(slug, r){
  if(!sb) throw new Error('No connection');
  const { error } = await sb.from('reviews').insert({
    company_slug: slug, author_name: r.name, author_email: r.email,
    rating: r.rating, body: r.body, status: 'Pending'
  });
  if(error){ console.error('submitReview', error); throw error; }
}
async function submitInquiry(slug, q){
  if(!sb) throw new Error('No connection');
  const { data, error } = await sb.from('inquiries').insert({
    company_slug: slug, from_name: q.name, from_email: q.email,
    from_company: q.company || null, phone: q.phone || null,
    subject: q.subject || null, body: q.body,
    quantity: q.quantity || null, part_number: q.part_number || null,
    status: 'New'
  }).select('id').maybeSingle();
  if(error){ console.error('submitInquiry', error); throw error; }
  return data;
}

/* ---- analytics ----
   visitor id is a random string kept in localStorage so repeat page loads by
   the same browser collapse into one unique hit at query time.

   Only set once the visitor has accepted analytics — see analytics.js, which
   owns the cx_consent key. Decline and we still record the view so the company
   sees its traffic; the row just carries no identifier, so it cannot be tied
   to anything or anyone. */
function visitorId(){
  try{
    if(localStorage.getItem('cx_consent') !== 'yes'){
      localStorage.removeItem('cx_v');      // clean up if they change their mind
      return null;
    }
    let v = localStorage.getItem('cx_v');
    if(!v){ v = Math.random().toString(36).slice(2) + Date.now().toString(36); localStorage.setItem('cx_v', v); }
    return v;
  }catch(e){ return null; }
}
function trackEvent(slug, kind, keyword){
  if(!sb || !slug) return;
  // fire and forget: analytics must never block or break the page
  sb.from('profile_events').insert({
    company_slug: slug, kind, keyword: keyword || null, visitor: visitorId()
  }).then(null, e => console.warn('trackEvent', e));
}

/* ---- owner reads/writes (RLS decides what is visible) ---- */
async function myCompanies(){
  if(!sb) return [];
  const { data, error } = await sb.rpc('my_companies');
  if(error){ console.error('myCompanies', error); return []; }
  return data || [];
}
/* A row-level-security refusal is NOT an error in PostgREST — a blocked update
   returns success with zero rows touched. Selecting the row back is the only
   way to tell "saved" from "silently discarded". */
async function updateCompany(slug, fields){
  if(!sb) return 'No connection';
  const { data, error } = await sb.from('companies').update(fields).eq('slug', slug).select('slug');
  if(error){ console.error('updateCompany', error); return error.message; }
  if(!data || !data.length) return 'nothing was saved — this account does not have permission to edit this company.';
  return null;
}
async function fetchMyListings(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:true });
  if(error){ console.error('fetchMyListings', error); return []; }
  return data || [];
}
async function fetchMyReviews(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('reviews').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:false });
  if(error){ console.error('fetchMyReviews', error); return []; }
  return data || [];
}
async function replyToReview(id, reply){
  if(!sb) return;
  const { error } = await sb.from('reviews').update({ reply }).eq('id', id);
  if(error) console.error('replyToReview', error);
}
async function fetchInquiries(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('inquiries').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:false });
  if(error){ console.error('fetchInquiries', error); return []; }
  return data || [];
}
async function setInquiryStatus(id, status){
  if(!sb) return;
  const { error } = await sb.from('inquiries').update({ status }).eq('id', id);
  if(error) console.error('setInquiryStatus', error);
}
async function fetchThread(inquiryId){
  if(!sb) return [];
  const { data, error } = await sb.from('inquiry_messages').select('*')
    .eq('inquiry_id', inquiryId).order('created_at');
  if(error){ console.error('fetchThread', error); return []; }
  return data || [];
}
async function postMessage(inquiryId, body){
  if(!sb) return 'No connection';
  const { error } = await sb.from('inquiry_messages').insert({ inquiry_id: inquiryId, body, author: 'supplier' });
  if(error){ console.error('postMessage', error); return error.message; }
  return null;
}
/* Views over a window, bucketed to suit it. Returns [{bucket, hits}]. */
async function companyViews(slug, fromIso, toIso, bucket){
  if(!sb || !slug) return [];
  const { data, error } = await sb.rpc('company_views',
    { p_slug: slug, p_from: fromIso, p_to: toIso, p_bucket: bucket || 'day' });
  if(error){ console.error('companyViews', error); return []; }
  return data || [];
}
async function companyStats(slug, days){
  if(!sb) return [];
  const { data, error } = await sb.rpc('company_stats', { p_slug: slug, p_days: days || 30 });
  if(error){ console.error('companyStats', error); return []; }
  return data || [];
}

/* ---- claiming ---- */
/* No account required: accounts are only created through Get Listed, so a
   claim is a request that staff verify and fulfil in the admin console. */
async function submitClaim(slug, c){
  if(!sb) return 'No connection';
  const user = await currentUser();
  const { error } = await sb.from('claims').insert({
    company_slug: slug, user_id: user ? user.id : null,
    email: c.email || (user && user.email) || '',
    name: c.name || null, role_title: c.role_title || null,
    evidence: c.evidence || null, status: 'Pending'
  });
  if(error){ console.error('submitClaim', error); return error.message; }
  return null;
}
async function fetchClaims(){
  if(!sb) return [];
  const { data, error } = await sb.from('claims').select('*').order('created_at', { ascending:false });
  if(error){ console.error('fetchClaims', error); return []; }
  return data || [];
}
/* Staff approval of a claim is what actually grants access. The claimant has no
   account when they ask, so approval attaches the login by email — create it in
   Supabase Auth first if it does not exist yet. */
async function decideClaim(claim, approve){
  if(!sb) return;
  if(approve){
    const { data, error } = await sb.rpc('attach_company_user',
      { p_slug: claim.company_slug, p_email: claim.email });
    if(error){ console.error('decideClaim attach', error); return error.message; }
    if(data === 'no-account'){
      return 'No login exists for ' + claim.email + ' yet. Create that user in Supabase Auth, then approve again.';
    }
  }
  const { error } = await sb.from('claims').update({ status: approve ? 'Approved' : 'Denied' }).eq('id', claim.id);
  if(error){ console.error('decideClaim', error); return error.message; }
  return null;
}

/* ---- staff moderation ---- */
async function fetchAllReviews(){
  if(!sb) return [];
  const { data, error } = await sb.from('reviews').select('*').order('created_at', { ascending:false });
  if(error){ console.error('fetchAllReviews', error); return []; }
  return data || [];
}
async function setReviewStatus(id, status){
  if(!sb) return;
  const { error } = await sb.from('reviews').update({ status }).eq('id', id);
  if(error) console.error('setReviewStatus', error);
}

/* Current window, the window before it, and the view->contact->quote funnel,
   in one round trip. Returns null on failure rather than zeros, so the portal
   can say "unavailable" instead of quietly reporting a bad month. */
async function companyInsights(slug, days){
  if(!sb || !slug) return null;
  const { data, error } = await sb.rpc('company_insights', { p_slug: slug, p_days: days || 30 });
  if(error){ console.error('company_insights', error); return null; }
  return (data && data[0]) || null;
}

/* Emails the supplier that a quote request has arrived.
   The recipient is decided server-side from the company slug — this call
   cannot name an address, or the site would be an open spam relay.
   Never throws: the request is already saved in the database and visible in
   the supplier's portal, so a failed notification must not fail the form. */
async function notifySupplier(slug, quote){
  try{
    const res = await fetch(SUPABASE_URL + '/functions/v1/notify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY },
      body: JSON.stringify({ kind: 'quote', company_slug: slug, quote: quote })
    });
    const out = await res.json().catch(() => null);
    if(!out || !out.ok) console.warn('supplier not notified:', out && out.error);
    return !!(out && out.ok);
  }catch(err){ console.warn('supplier notification failed', err); return false; }
}

/* Every company, including suspended ones — staff only, enforced by the
   companies_read policy rather than by asking nicely here. */
async function fetchAllCompanies(){
  if(!sb) return [];
  const { data, error } = await sb.from('companies')
    .select('slug, name, handle, email, published, suspended_at, created_at')
    .order('name');
  if(error){ console.error('fetchAllCompanies', error); return []; }
  return data || [];
}

/* Staff reads for the demand data. Both are refused by the database for
   anybody who is not staff, so this is convenience, not the control. */
async function fetchTopSearches(days, missedOnly){
  if(!sb) return [];
  const { data, error } = await sb.rpc('top_searches',
    { p_days: days || 30, p_missed_only: !!missedOnly });
  if(error){ console.error('top_searches', error); return []; }
  return data || [];
}
async function fetchWanted(){
  if(!sb) return [];
  const { data, error } = await sb.from('wanted').select('*')
    .order('at', { ascending:false }).limit(200);
  if(error){ console.error('fetchWanted', error); return []; }
  return data || [];
}
async function setWantedHandled(id, handled){
  if(!sb) return 'Not connected.';
  const { error } = await sb.from('wanted').update({ handled: !!handled }).eq('id', id);
  if(error){ console.error('setWantedHandled', error); return error.message; }
  return '';
}

/* The staff audit trail. Append-only in the database, so this is a faithful
   record of what was done and by whom — including by us. */
async function fetchSecurityLog(limit){
  if(!sb) return [];
  const { data, error } = await sb.from('security_log')
    .select('*').order('at', { ascending:false }).limit(limit || 100);
  if(error){ console.error('fetchSecurityLog', error); return []; }
  return data || [];
}

/* ---- suspension ----
   Deliberately not deletion. A suspended company keeps every row it had, so a
   dispute can be reversed and a returning customer picks up where they left
   off. The database does the enforcing: a suspended listing disappears from
   the directory and from keyword results, and its owner can neither edit it
   nor lift the suspension. See set_company_suspended() in the migration. */
async function suspendCompany(slug, suspend, reason){
  if(!sb) return 'Not connected.';
  const { error } = await sb.rpc('set_company_suspended',
    { p_slug: slug, p_suspend: !!suspend, p_reason: reason || null });
  if(error){ console.error('set_company_suspended', error); return error.message; }
  return '';
}
async function suspendProfile(handle, suspend, reason){
  if(!sb) return 'Not connected.';
  const { error } = await sb.rpc('set_profile_suspended',
    { p_handle: handle, p_suspend: !!suspend, p_reason: reason || null });
  if(error){ console.error('set_profile_suspended', error); return error.message; }
  return '';
}

/* ---- logo + gallery image storage (public bucket "logos") ---- */
async function uploadImage(file){ return uploadLogo(file); }

/* Send anyone who is not a signed-in admin back to the portal. There is one
   sign-in for the whole site now; admin is a property of the account. */
async function requireStaff(){
  const user = await currentUser();
  if(!user){ location.href = 'portal'; return false; }
  const staff = await checkStaff();
  if(!staff){
    document.body.innerHTML = '<div style="max-width:520px;margin:80px auto;font-family:Arial,sans-serif;text-align:center;color:#1a1a1a">'
      + '<h2>Not authorized</h2><p style="color:#5f6368">This account isn’t on the Circuits.com staff list. '
      + 'Sign in with an account that has admin.</p><p><a href="portal" style="color:#5f9b00;font-weight:600">Back to your profile</a></p></div>';
    return false;
  }
  return true;
}
