/* ===== Circuits.com — Supabase-backed data store =====
   Real persistence shared across all clients and devices.
   Requires the Supabase JS client (loaded from CDN) before this file.
   The URL and publishable key below are PUBLIC by design (safe to embed);
   all access is enforced server-side by Row Level Security. */

const SUPABASE_URL = 'https://ghpruernzhjwsgsezdyn.supabase.co';
const SUPABASE_KEY = 'sb_publishable_zmOQinynNkuWdHUeHrFdDA_y6UnLyL4';

const sb = (window.supabase && window.supabase.createClient)
  ? window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY)
  : null;

/* Column lists for the PUBLIC (logged-out) reads. Anonymous visitors are
   granted SELECT on every column EXCEPT the private account email
   (applications.owner_email / reviews.author_email), which is why these reads
   must NOT use select('*') — `*` references the ungranted column and Postgres
   denies the whole query, which once made every listing vanish for logged-out
   visitors. Signed-in reads (portal, admin) keep select('*'); they have the
   full grant. Keep these in sync with the table columns. */
const APP_PUBLIC_COLS = 'id, created_at, company, contact, email, phone, website, logo, keywords, banner, badge, message, terms, fee, status, keyword, paused, listing_price, banner_price, badge_price, locked_position, docs, description, company_slug, company_handle, requested_handle, keyword_norm, certifications, team, gallery, reviews_enabled';
const REVIEW_PUBLIC_COLS = 'id, company_slug, application_id, author_name, rating, body, reply, status, created_at';

/* ---- pricing ----
   Beta rates. Original owners keep these for as long as their subscription
   stays active, so these numbers are a floor we honour, not a list price.
   Yearly works out to ten months, i.e. two months free. */
const BASE_FEE = 99, BANNER_FEE = 399, BADGE_FEE = 49;
const BASE_FEE_YEAR = 999, BANNER_FEE_YEAR = 3999, BADGE_FEE_YEAR = 399;
function effPrice(v, fallback){
  return (v==null || v==='' || isNaN(Number(v))) ? fallback : Number(v);
}
function appPrice(a){
  let p = effPrice(a && a.listing_price, BASE_FEE);
  if(a && a.banner) p += effPrice(a.banner_price, BANNER_FEE);
  if(a && a.badge)  p += effPrice(a.badge_price, BADGE_FEE);
  return p;
}
function appPriceLabel(a){ return (a && a.fee) ? a.fee : ('$' + appPrice(a) + '/mo'); }

/* ---- read ---- */
async function fetchApplications(){
  if(!sb) return [];
  // oldest first — new listings join at the BOTTOM of the list
  // (earlier claims keep the higher permanent position)
  // secondary sort by id keeps rows from jumping when timestamps tie
  const { data, error } = await sb.from('applications').select('*')
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.error('fetchApplications', error); return []; }
  return data || [];
}
async function fetchApproved(){
  if(!sb) return [];
  const { data, error } = await sb.from('applications').select('*').eq('status','Approved')
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.error('fetchApproved', error); return []; }
  return data || [];
}
/* ===== Keyword matching ruleset =====
   1. Lowercase everything.
   2. Strip every non-letter/digit (hyphens, spaces, punctuation) — "semi-conductors" == "semi conductors" == "semiconductors".
   3. Singularize the plural tail — "sensors" == "sensor", "switches" == "switch", "batteries" == "battery".
   4. EXACT match only after normalization. No substring/partial matching, so
      "list test 2" never matches "list test 3" and "zzz" only matches "zzz".
   5. Blank/empty keywords never match anything. */
function singularize(n){
  if(n.length>4 && n.endsWith('ies')) return n.slice(0,-3)+'y';   // batteries -> battery
  if(n.length>3 && /(?:x|z|ch|sh)es$/.test(n)) return n.slice(0,-2); // switches -> switch, boxes -> box
  if(n.length>3 && n.endsWith('s') && !n.endsWith('ss')) return n.slice(0,-1); // sensors -> sensor, fuses -> fuse
  return n;
}
function normKw(s){
  return singularize((s||'').toLowerCase().replace(/[^a-z0-9]/g,''));
}
/* Approval-level cleanup for stored keywords: lowercase, no hyphens, no plurals. */
function cleanKw(s){
  let v = (s||'').toLowerCase().replace(/-+/g,' ').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();
  return v.replace(/([a-z0-9]+)$/, w => singularize(w));
}
/* One live listing per company for a searched keyword (skips paused ones).
   Postgres does the matching on an index over applications.keyword_norm, which
   is generated by norm_kw() — the SQL twin of normKw() above. This used to pull
   every approved listing into the browser and filter here, so search got slower
   with every listing sold. Still oldest-first: earlier claims keep the higher
   permanent position. */
async function fetchApprovedByKeyword(keyword){
  /* No client (CDN blocked, offline) is a FAILED lookup, not an empty one —
     returning [] here showed "no one is listed" for keywords already sold. */
  if(!sb) throw new Error('no connection');
  const k = normKw(keyword);
  if(!k) return [];
  const { data, error } = await sb.from('applications').select(APP_PUBLIC_COLS)
    .eq('status','Approved').eq('paused', false).eq('keyword_norm', k)
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  /* Throw, don't return []. An empty array here means "nobody owns this
     keyword", which the results page turns into a pitch to buy it. If the
     request merely failed we would be offering a keyword somebody already
     owns — and could sell it twice. Callers must tell the two apart. */
  if(error){ console.error('fetchApprovedByKeyword', error); throw error; }
  const seen = new Set(), out = [];
  for(const a of (data || [])){ if(seen.has(a.company)) continue; seen.add(a.company); out.push(a); }
  return out;
}

/* ---- what people look for ----
   Logged for every search, found or not. Deliberately anonymous: the term, the
   number of hits and the time, nothing that ties it to a person. The value is
   the aggregate — which keywords are wanted and which ones we cannot answer.

   Never awaited and never surfaced: a failure to log must not slow a search
   down or show the searcher an error about our own bookkeeping. */
function logSearch(term, hits){
  if(!sb) return;
  const q = (term || '').trim().slice(0, 120);
  if(!q) return;
  try{
    sb.from('searches').insert({ q, q_norm: normKw(q).slice(0, 120), hits: hits | 0 })
      .then(({ error }) => { if(error) console.warn('logSearch', error.message); });
  }catch(err){ console.warn('logSearch failed', err); }
}

/* A buyer who found nothing, asking to be told when somebody lists. This one
   the caller DOES wait on, because they are owed an answer. */
async function registerWanted(keyword, email, note){
  if(!sb) return 'No connection';
  const { error } = await sb.from('wanted').insert({
    keyword: (keyword || '').trim().slice(0, 120),
    email: (email || '').trim().slice(0, 320),
    note: (note || '').trim().slice(0, 1000) || null
  });
  if(error){ console.error('registerWanted', error); return error.message; }
  return '';
}

/* Related listings when the exact keyword has none: split what they typed and
   look for a listing on any single word of it, so "crystal oscillator" reaches
   the company listed under "oscillators". Clearly labelled as related in the
   page — an exact keyword is what companies pay for and must not be diluted. */
async function fetchRelatedByKeyword(keyword){
  if(!sb) return [];
  const words = (keyword || '').toLowerCase().split(/[^a-z0-9]+/).filter(w => w.length > 2);
  const terms = [...new Set(words.map(normKw))].filter(Boolean).slice(0, 6);
  if(!terms.length) return [];
  const { data, error } = await sb.from('applications').select(APP_PUBLIC_COLS)
    .eq('status','Approved').eq('paused', false).in('keyword_norm', terms)
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.warn('fetchRelatedByKeyword', error.message); return []; }
  const seen = new Set(), out = [];
  for(const a of (data || [])){ if(seen.has(a.company)) continue; seen.add(a.company); out.push(a); }
  return out;
}

/* ---- company logo storage (Supabase Storage, public bucket "logos") ---- */
async function uploadLogo(file){
  if(!sb || !file) return '';
  const ext = (file.name.split('.').pop() || 'png').toLowerCase().replace(/[^a-z0-9]/g,'');
  const path = Date.now() + '-' + Math.random().toString(36).slice(2,8) + '.' + ext;
  const { error } = await sb.storage.from('logos').upload(path, file, { contentType: file.type, cacheControl: '31536000' });
  if(error){ console.error('uploadLogo', error); return ''; }
  return sb.storage.from('logos').getPublicUrl(path).data.publicUrl;
}
function isLogoUrl(s){ return /^https?:\/\//i.test(s||''); }

/* Field-format validators. app.js declares the same three (contact and index
   load app.js without store.js); keep both copies identical. Here so pages
   that load only store.js — the admin dashboard — can gate their saves too. */
function isValidEmail(s){ return /^[^\s@]+@[^\s@]+\.[a-z]{2,}$/i.test((s||'').trim()); }
function isValidPhone(s){ const d=(s||'').replace(/\D/g,''); return d.length>=10 && d.length<=15; }
function isValidWebsite(s){ return /^(https?:\/\/)?([a-z0-9-]+\.)+[a-z]{2,}([\/?#]\S*)?$/i.test((s||'').trim()); }
function isValidYear(s){ return /^(18|19|20)\d{2}$/.test((s||'').trim()); }

/* ---- listing documentation storage (Supabase Storage, public bucket "docs") ---- */
async function uploadDoc(file){
  if(!sb || !file) return null;
  const ext = (file.name.split('.').pop() || 'pdf').toLowerCase().replace(/[^a-z0-9]/g,'');
  const path = Date.now() + '-' + Math.random().toString(36).slice(2,8) + '.' + ext;
  const { error } = await sb.storage.from('docs').upload(path, file, { contentType: file.type, cacheControl: '31536000' });
  if(error){ console.error('uploadDoc', error); return null; }
  return { name: file.name, url: sb.storage.from('docs').getPublicUrl(path).data.publicUrl };
}

/* ---- write ---- */
/* Join form: one submission becomes one row per keyword. */
async function addApplicationKeywords(base, keywords){
  if(!sb) throw new Error('No connection');
  const list = (keywords && keywords.length) ? keywords.map(cleanKw) : [''];
  const rows = list.map(kw => Object.assign({}, base, {
    keyword: kw, keywords: kw ? [kw] : [], status: base.status || 'Pending'
  }));
  const { error } = await sb.from('applications').insert(rows);
  if(error){ console.error('addApplicationKeywords', error); throw error; }
  return rows;
}
async function updateAppStatus(id, status){
  if(!sb) return null;
  const { error } = await sb.from('applications').update({ status }).eq('id', id);
  if(error) console.error('updateAppStatus', error);
  return error || null;
}
/* Approve every keyword row for a company (Add Listing dropdown). */
async function approveCompany(company){
  if(!sb) return;
  const { error } = await sb.from('applications').update({ status:'Approved', paused:false }).eq('company', company);
  if(error) console.error('approveCompany', error);
}
/* Returns null on a real change, or a truthy value when nothing changed.
   A row that RLS refuses comes back as an UPDATE affecting zero rows with NO
   error (a PostgREST/Postgres quirk), so a plain "no error" check reported
   success on a change that never happened — e.g. a suspended listing. Asking
   for the changed row back and checking it is the only reliable signal. */
async function setPaused(id, paused){
  if(!sb) return { message: 'No connection' };
  const { data, error } = await sb.from('applications').update({ paused }).eq('id', id).select('id');
  if(error){ console.error('setPaused', error); return error; }
  if(!data || !data.length){ console.warn('setPaused changed no rows (blocked?)', id); return { message: 'not-updated' }; }
  return null;
}
async function updateApplication(id, fields){
  if(!sb) return null;
  if('keyword' in fields){ fields.keyword = cleanKw(fields.keyword); fields.keywords = fields.keyword ? [fields.keyword] : []; }
  const { error } = await sb.from('applications').update(fields).eq('id', id);
  if(error) console.error('updateApplication', error);
  return error || null;
}
/* What a supplier may change on their own listing.
   The database already enforces this — applications_lock_billing() silently
   reverts keyword, banner, badge, price, fee and status for anyone who is not
   staff. That silence is the danger: a form offering those fields would appear
   to save and quietly change nothing. So the allowed set is named here too, and
   anything else is dropped before the request rather than after.

   Commercial terms stay with staff because they are what the company is billed
   for. Its own words and its own datasheets are not. */
const LISTING_OWNER_FIELDS = ['description', 'docs', 'certifications', 'team', 'gallery', 'reviews_enabled'];

async function updateMyListing(id, fields){
  if(!sb) return 'No connection';
  const clean = {};
  for(const k of LISTING_OWNER_FIELDS) if(k in fields) clean[k] = fields[k];
  if(!Object.keys(clean).length) return null;
  if(typeof clean.description === 'string'){
    clean.description = clean.description.trim().slice(0, 300);   // matches the CHECK constraint
    if(!clean.description) clean.description = null;
  }
  const { error } = await sb.from('applications').update(clean).eq('id', id);
  if(error){ console.error('updateMyListing', error); return error.message; }
  return null;
}

async function deleteApplication(id){
  if(!sb) return;
  const { error } = await sb.from('applications').delete().eq('id', id);
  if(error) console.error('deleteApplication', error);
}

/* ---- auth (staff) ---- */
async function currentUser(){ if(!sb) return null; const { data } = await sb.auth.getUser(); return data ? data.user : null; }
async function checkStaff(){ if(!sb) return false; const { data, error } = await sb.rpc('is_staff'); if(error){ console.error('is_staff', error); return false; } return !!data; }
/* Sign in with an email OR a Circuits.com username.
   Supabase only knows emails, so a username has to become one. That
   resolution used to happen in the browser via email_for_login(), which
   handed anyone who knew a handle the account's email — a harvesting oracle.
   It now happens inside the `auth` edge function (service role): the function
   resolves the handle, performs the password grant, and returns only the
   session — the address never comes back to the page. A wrong username and a
   wrong password are answered identically, so the endpoint still cannot be
   used to discover who is registered. */
async function signIn(identifier, password){
  const id = (identifier || '').trim();
  if(!sb) return { error: { message: 'We could not reach the sign-in service. Check your connection and try again.' } };
  if(id && !id.includes('@')){
    try{
      const res = await fetch(SUPABASE_URL + '/functions/v1/auth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY },
        body: JSON.stringify({ action: 'signin', identifier: id, password })
      });
      const out = await res.json().catch(() => ({}));
      if(out && out.session && out.session.access_token){
        const { error } = await sb.auth.setSession({
          access_token: out.session.access_token,
          refresh_token: out.session.refresh_token
        });
        return { error };
      }
      return { error: (out && out.error) ? out.error : { message: 'Invalid login credentials' } };
    }catch(e){
      console.warn('username sign-in failed', e);
      return { error: { message: 'We could not reach the sign-in service. Check your connection and try again.' } };
    }
  }
  return sb.auth.signInWithPassword({ email: id, password });
}
/* The confirmation link lands on /portal — the signed-in session in the URL is
   picked up there and the new account sees its own portal. Without this it fell
   back to whatever page the project's Site URL points at, which was the
   password-reset sheet — alarming for someone who just set a password. */
async function signUp(email, password){
  if(!sb) return { error: { message: 'We could not reach the sign-up service. Check your connection and try again.' } };
  return sb.auth.signUp({ email, password,
    options: { emailRedirectTo: location.origin + '/portal' } });
}

/* ---- password reset ----
   Accepts an email OR a username, the same as signing in. Always reports
   success: telling someone "no account with that email" turns this form into
   a way to discover who is registered. */
async function requestPasswordReset(identifier){
  if(!sb) return 'No connection';
  let email = (identifier || '').trim();
  if(email && !email.includes('@')){
    /* A username is resolved and the recovery email sent server-side, so the
       address is never exposed. The answer is always the same whether or not
       the username exists — see the `auth` edge function. */
    try{
      await fetch(SUPABASE_URL + '/functions/v1/auth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY },
        body: JSON.stringify({ action: 'reset', identifier: email })
      });
    }catch(e){ console.warn('username reset lookup failed', e); }
    return '';
  }
  if(email.includes('@')){
    const { error } = await sb.auth.resetPasswordForEmail(email, {
      redirectTo: location.origin + '/reset'
    });
    if(error){
      console.warn('resetPasswordForEmail', error.message);
      /* Whether the send FAILED is not a secret — it says nothing about who is
         registered — and swallowing it is worse than useless: the visitor is
         told to check an inbox that will never receive anything. The account's
         existence stays hidden; the outage does not. */
      const status = error.status || error.code;
      if(status === 429 || /rate limit/i.test(error.message || '')){
        /* Two different limits arrive as 429: a short per-address wait after a
           request that DID send, and the project-wide hourly cap. Telling
           someone to wait an hour when it is really 45 seconds sends them away
           for no reason, so use the wait the server actually reports. */
        const secs = (/after (\d+) seconds?/i.exec(error.message || '') || [])[1];
        if(secs){
          return 'A reset link was just sent. If it has not arrived, you can ask for another in '
               + secs + ' seconds.';
        }
        return 'Too many reset emails have been sent from Circuits.com in the last hour. '
             + 'Please try again shortly, or email support@circuits.com and we will reset it for you.';
      }
      return 'We could not send the reset email just now. Please try again in a few minutes, '
           + 'or email support@circuits.com.';
    }
  }
  return '';
}
/* Called on /reset. Supabase puts a recovery session in the URL, which the
   client picks up on load, so this is just a password change. */
async function setNewPassword(password){
  if(!sb) return 'No connection';
  const { error } = await sb.auth.updateUser({ password });
  return error ? error.message : '';
}
async function signOut(){ if(sb) await sb.auth.signOut(); }
/* Ends every session on every device, not just this browser. What you want
   after a shared laptop or a lost phone. */
async function signOutEverywhere(){
  if(!sb) return 'Not connected.';
  const { error } = await sb.auth.signOut({ scope: 'global' });
  if(error){ console.error('signOutEverywhere', error); return error.message; }
  return '';
}
/* Returns 'deleted', or 'still_owns_listing' when the account manages a paid
   listing — see delete_own_account() for why that case is refused. */
async function deleteOwnAccount(){
  if(!sb) return 'error';
  const { data, error } = await sb.rpc('delete_own_account');
  if(error){ console.error('delete_own_account', error); return 'error'; }
  return data;
} async function loadPrefs(page){ if(!sb) return null; const { data, error } = await sb.from('admin_prefs').select('prefs').eq('page', page).maybeSingle(); if(error){ console.error('loadPrefs', error); return null; } return data ? data.prefs : null; } async function savePrefs(page, prefs){ if(!sb) return; const { data } = await sb.auth.getUser(); if(!data || !data.user) return; const { error } = await sb.from('admin_prefs').upsert({ user_id: data.user.id, page, prefs, updated_at: new Date().toISOString() }, { onConflict: 'page' }); if(error) console.error('savePrefs', error); }

/* ===================================================================
   Company profiles
   =================================================================== */

/* Must stay identical to the SQL slugify() in the database. */
function slugify(s){
  return (s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
}
/* A company's public address is its handle, straight off the root:
   circuits.com/zzzelec — short enough to put on an advert. */
function profileUrl(handle){
  return handle ? '/' + handle : '';
}
/* Must match handle_ok() in the database. */
function handleFormatOk(h){
  return /^[a-z0-9]([a-z0-9_-]*[a-z0-9])?$/.test(h||'')
      && h.length >= 3 && h.length <= 32
      && !/--|__|_-|-_/.test(h);
}
/* Is this handle free? Returns '' if available, or the reason it is not.
   circuits.com/<name> is one namespace shared by listings and profiles, so the
   database answers this — the same function the insert triggers use. */
const HANDLE_WHY = {
  format:   '3–32 characters: letters, numbers, and single hyphens or underscores between them.',
  reserved: 'That name is reserved by Circuits.com.',
  company:  'Taken by a company listing.',
  profile:  'Taken by another profile.'
};
async function handleAvailable(handle, ownSlug, ownUser){
  const h = (handle||'').toLowerCase().trim();
  if(!handleFormatOk(h)) return HANDLE_WHY.format;
  if(!sb) return 'No connection';
  const { data, error } = await sb.rpc('handle_taken',
    { p_handle: h, p_user: ownUser || null, p_slug: ownSlug || null });
  if(error){ console.error('handle_taken', error); return 'Could not check that name right now.'; }
  return HANDLE_WHY[data] || '';
}

/* Is a real account behind this listing? Drives the Unclaimed badge. */
async function companyClaimed(slug){
  if(!sb || !slug) return true;   // fail closed: never label a listing unclaimed by mistake
  const { data, error } = await sb.rpc('company_claimed', { p_slug: slug });
  if(error){ console.error('company_claimed', error); return true; }
  return !!data;
}

/* A profile run by a Circuits.com admin carries our own mark. Fail closed the
   other way round from companyClaimed: if we cannot tell, do not award the
   badge — wrongly claiming a listing is ours is worse than missing one. */
async function companyRunByStaff(slug){
  if(!sb || !slug) return false;
  const { data, error } = await sb.rpc('company_run_by_staff', { p_slug: slug });
  if(error){ console.error('company_run_by_staff', error); return false; }
  return !!data;
}

/* Same mark, same rule, for a PERSON profile: an admin's own page carries the
   Circuits.com badge. Decided by the database, and fails closed. */
async function profileRunByStaff(handle){
  if(!sb || !handle) return false;
  const { data, error } = await sb.rpc('profile_run_by_staff', { p_handle: handle });
  if(error){ console.error('profile_run_by_staff', error); return false; }
  return !!data;
}

/* ---- profiles: a person, separate from any company listing ---- */
/* Only these columns are readable by visitors: email, phone and resume_path are
   private (talent marketplace, 2026-09-02) and leave the table solely through
   my_profile() for the owner and talent_contact() for subscribed companies. */
const PROFILE_PUBLIC_COLS = 'user_id, handle, display_name, created_at, updated_at, suspended_at, title, years, bio, talent_listed, talent_hidden';
async function fetchProfileByHandle(handle){
  if(!sb || !handle) return null;
  const { data, error } = await sb.from('profiles').select(PROFILE_PUBLIC_COLS)
    .ilike('handle', (handle||'').trim()).maybeSingle();
  // same reasoning as fetchCompanyByHandle: never invent a free address
  if(error){ console.error('fetchProfileByHandle', error); throw error; }
  return data;
}
async function myProfile(){
  if(!sb) return null;
  const { data, error } = await sb.rpc('my_profile');
  if(error){ console.error('my_profile', error); return null; }
  return (data && data[0]) || null;
}
/* An account from before profiles existed (staff, early owners) has no row.
   The portal creates one on first save instead of sending them to /register. */
async function createMyProfile(handle, displayName){
  if(!sb) return 'No connection';
  const u = await currentUser();
  if(!u) return 'Not signed in';
  const { error } = await sb.from('profiles')
    .insert({ user_id: u.id, handle, display_name: displayName || null, email: u.email });
  return error ? error.message : '';
}
async function updateMyProfile(fields){
  if(!sb) return 'No connection';
  const u = await currentUser();
  if(!u) return 'Not signed in';
  const { data, error } = await sb.from('profiles').update(fields).eq('user_id', u.id).select('user_id');
  if(error) return error.message;
  if(!data || !data.length) return 'That change was refused.';
  return '';
}

/* ---- talent marketplace (MVP2): a profile that opts in to the Recruits Directory ---- */
/* the keywords the owner wants to be found under; the database normalises,
   de-duplicates and caps them at ten */
async function setTalentKeywords(keywords){
  if(!sb) return { error: 'No connection' };
  const { data, error } = await sb.rpc('set_talent_keywords', { p_keywords: keywords || [] });
  if(error) return { error: /keyword_limit/.test(error.message) ? 'Ten keywords is the limit.' : error.message };
  return { keywords: data || [] };
}
/* the resume: one PDF per person at <user_id>/resume.pdf in the private bucket */
async function uploadResume(file){
  if(!sb || !file) return { error: 'No file' };
  const u = await currentUser(); if(!u) return { error: 'Not signed in' };
  const path = u.id + '/resume.pdf';
  const { error } = await sb.storage.from('resumes').upload(path, file, { contentType: 'application/pdf', upsert: true });
  if(error) return { error: error.message };
  const err = await updateMyProfile({ resume_path: path });
  return err ? { error: err } : { path };
}
async function removeResume(){
  if(!sb) return 'No connection';
  const u = await currentUser(); if(!u) return 'Not signed in';
  await sb.storage.from('resumes').remove([u.id + '/resume.pdf']);
  return updateMyProfile({ resume_path: null });
}
/* a short-lived link to a resume: works for the owner and for subscribed companies */
async function resumeLink(path){
  if(!sb || !path) return '';
  const { data, error } = await sb.storage.from('resumes').createSignedUrl(path, 300);
  if(error){ console.warn('resumeLink', error.message); return ''; }
  return data.signedUrl;
}
/* the directory: public metadata only, never a name or a handle */
async function talentSearch(keyword){
  if(!sb) throw new Error('no connection');
  const { data, error } = await sb.rpc('talent_search', { p_keyword: keyword || '' });
  if(error) throw error;
  return data || [];
}
/* the unblur: only answers for the owner, staff, or a company whose talent
   subscription (companies.talent_access_until) is active */
async function talentContact(userId){
  if(!sb) return null;
  const { data, error } = await sb.rpc('talent_contact', { p_user: userId });
  if(error) return null;
  return (data && data[0]) || null;
}
async function fetchTalentKeywords(userId){
  if(!sb || !userId) return [];
  const { data, error } = await sb.from('talent_keywords').select('keyword').eq('user_id', userId).order('keyword');
  if(error){ console.warn('fetchTalentKeywords', error.message); return []; }
  return (data || []).map(r => r.keyword);
}
/* ---- jobs (MVP2): posted by a company owner, live once staff mark it paid ---- */
async function postJob(slug, fields){
  if(!sb) return { error: 'No connection' };
  const { data, error } = await sb.from('jobs')
    .insert({ company_slug: slug, title: fields.title, location: fields.location || null,
              description: fields.description || null, apply_email: fields.apply_email || null })
    .select('id').single();
  if(error) return { error: error.message };
  return { id: data.id };
}
async function updateJob(id, fields){
  if(!sb) return 'No connection';
  const { data, error } = await sb.from('jobs').update(fields).eq('id', id).select('id');
  if(error) return error.message;
  if(!data || !data.length) return 'That change was refused.';
  return '';
}
async function setJobKeywords(id, keywords){
  if(!sb) return { error: 'No connection' };
  const { data, error } = await sb.rpc('set_job_keywords', { p_job: id, p_keywords: keywords || [] });
  if(error) return { error: /keyword_limit/.test(error.message) ? 'Ten keywords is the limit.' : error.message };
  return { keywords: data || [] };
}
/* a company's own jobs, with their keywords; owners see them paid or not */
async function myJobs(slug){
  if(!sb || !slug) return [];
  const { data, error } = await sb.from('jobs').select('*, job_keywords(keyword)')
    .eq('company_slug', slug).order('created_at', { ascending: false });
  if(error){ console.error('myJobs', error); return []; }
  return (data || []).map(j => ({ ...j, keywords: (j.job_keywords || []).map(k => k.keyword).sort() }));
}
/* the public board: live jobs under a keyword, or every live job when blank */
async function jobSearch(keyword){
  if(!sb) throw new Error('no connection');
  const { data, error } = await sb.rpc('job_search', { p_keyword: keyword || '' });
  if(error) throw error;
  return data || [];
}
async function myApplications(){
  if(!sb) return [];
  const { data, error } = await sb.rpc('my_applications');
  if(error) return [];
  return data || [];
}
/* apply once; the employer is emailed by the notify function afterwards */
async function applyToJob(jobId, note){
  if(!sb) return 'No connection';
  const u = await currentUser(); if(!u) return 'Not signed in';
  const { error } = await sb.from('job_applications').insert({ job_id: jobId, user_id: u.id, note: (note || '').trim() || null });
  if(error) return /duplicate|unique/i.test(error.message) ? 'You already applied to this job.' : error.message;
  try{
    const { data: s } = await sb.auth.getSession();
    const jwt = s && s.session && s.session.access_token;
    await fetch(SUPABASE_URL + '/functions/v1/notify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY, Authorization: 'Bearer ' + jwt },
      body: JSON.stringify({ kind: 'job-apply', job_id: jobId })
    });
  }catch(e){ console.warn('employer not notified', e); }
  return '';
}
async function jobApplicants(jobId){
  if(!sb) return [];
  const { data, error } = await sb.rpc('job_applicants', { p_job: jobId });
  if(error){ console.error('jobApplicants', error); return []; }
  return data || [];
}

/* ---- staff: recruits, talent access, job payments ---- */
async function fetchRecruits(){
  if(!sb) return [];
  const { data, error } = await sb.from('profiles')
    .select('user_id, handle, display_name, title, years, talent_listed, talent_hidden, updated_at')
    .eq('talent_listed', true).order('updated_at', { ascending: false }).limit(500);
  if(error){ console.error('fetchRecruits', error); return []; }
  return data || [];
}
async function setTalentHidden(userId, hidden){
  if(!sb) return 'No connection';
  const { data, error } = await sb.from('profiles').update({ talent_hidden: !!hidden }).eq('user_id', userId).select('user_id');
  if(error) return error.message;
  if(!data || !data.length) return 'That change was refused.';
  return '';
}
async function setTalentAccess(slug, untilIso){
  if(!sb) return 'No connection';
  const { data, error } = await sb.from('companies').update({ talent_access_until: untilIso }).eq('slug', slug).select('slug');
  if(error) return error.message;
  if(!data || !data.length) return 'That change was refused.';
  return '';
}
async function fetchAllJobs(){
  if(!sb) return [];
  const { data, error } = await sb.from('jobs').select('*, job_keywords(keyword), companies(name, handle)')
    .order('created_at', { ascending: false }).limit(500);
  if(error){ console.error('fetchAllJobs', error); return []; }
  return (data || []).map(j => ({ ...j, keywords: (j.job_keywords || []).map(k => k.keyword).sort(),
    company_name: j.companies ? j.companies.name : j.company_slug, company_handle: j.companies ? j.companies.handle : null }));
}
async function hasTalentAccess(){
  if(!sb) return false;
  const { data } = await sb.rpc('has_talent_access');
  return !!data;
}
/* Register: the account and the circuits.com address are created together.
   The handle rides along as signup metadata because email confirmation means
   there is no session yet — a trigger turns it into the profile row, so the
   address is held from the moment the account exists. */
async function registerProfile(email, password, handle, displayName){
  if(!sb) return 'No connection';
  const { error } = await sb.auth.signUp({
    email, password,
    options: {
      data: { handle: (handle||'').toLowerCase().trim(), display_name: displayName || '' },
      emailRedirectTo: location.origin + '/portal'   // confirmation lands on the portal, not the reset sheet
    }
  });
  return error ? error.message : '';
}

/* ---- public reads ---- */
async function fetchCompany(slug){
  if(!sb || !slug) return null;
  const { data, error } = await sb.from('companies').select('*').eq('slug', slug).maybeSingle();
  if(error){ console.error('fetchCompany', error); return null; }
  return data;
}
/* Public pages address a company by its handle, not its internal slug. */
async function fetchCompanyByHandle(handle){
  if(!sb || !handle) return null;
  const { data, error } = await sb.from('companies')
    .select('*').eq('handle', (handle||'').toLowerCase()).maybeSingle();
  // null means "this address is free"; a failed lookup must not claim that
  if(error){ console.error('fetchCompanyByHandle', error); throw error; }
  return data;
}
/* Live keywords for a company, in the permanent order they were claimed. */
async function fetchCompanyKeywords(slug){
  if(!sb || !slug) return [];
  const { data, error } = await sb.from('applications').select(APP_PUBLIC_COLS)
    .eq('company_slug', slug).eq('status','Approved')
    .order('created_at', { ascending:true });
  if(error){ console.error('fetchCompanyKeywords', error); return []; }
  return (data||[]).filter(r => !r.paused && r.keyword);
}
async function fetchReviews(slug){
  if(!sb || !slug) return [];
  const { data, error } = await sb.from('reviews').select(REVIEW_PUBLIC_COLS)
    .eq('company_slug', slug).eq('status','Approved')
    .order('created_at', { ascending:false });
  if(error){ console.error('fetchReviews', error); return []; }
  return data || [];
}
/* ---- public writes ---- */
async function submitReview(slug, r){
  if(!sb) throw new Error('No connection');
  const { error } = await sb.from('reviews').insert({
    company_slug: slug, application_id: r.application_id || null, author_name: r.name, author_email: r.email,
    rating: r.rating, body: r.body, status: 'Pending'
  });
  if(error){ console.error('submitReview', error); throw error; }
}
/* Returns { id, token }. The token is the buyer's only way back to this
   conversation — they have no account, by design, and anon cannot read the
   table. It goes in their confirmation email and nowhere else. */
async function submitInquiry(slug, q){
  if(!sb) throw new Error('No connection');
  const { data, error } = await sb.rpc('create_inquiry', {
    p_slug: slug, p_name: q.name, p_email: q.email, p_company: q.company || null,
    p_phone: q.phone || null, p_subject: q.subject || null, p_body: q.body,
    p_quantity: q.quantity || null, p_part_number: q.part_number || null
  });
  if(error){ console.error('submitInquiry', error); throw error; }
  return data || null;
}

/* ---- the buyer's side of the conversation ----
   No account: the token in their emailed link is the credential. It reaches a
   SECURITY DEFINER function that returns one thread and nothing else, so the
   tables stay closed to anon. */
async function fetchThreadByToken(token){
  if(!sb || !token) return null;
  const { data, error } = await sb.rpc('thread_by_token', { p_token: token });
  if(error){ console.error('thread_by_token', error); throw error; }
  return data || null;
}
async function postBuyerMessage(token, body){
  if(!sb) return 'no-connection';
  const { data, error } = await sb.rpc('post_buyer_message', { p_token: token, p_body: body });
  if(error){ console.error('post_buyer_message', error); return error.message; }
  return data;                       // 'ok' | 'empty' | 'closed' | 'rate-limited' | 'not-found'
}

/* Tells the buyer a reply is waiting. The supplier must be signed in: the
   function checks they own the thread before it will email anyone. */
async function notifyBuyerOfReply(inquiryId, body){
  try{
    const { data: s } = await sb.auth.getSession();
    const jwt = s && s.session && s.session.access_token;
    if(!jwt) return false;
    const res = await fetch(SUPABASE_URL + '/functions/v1/notify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY, Authorization: 'Bearer ' + jwt },
      body: JSON.stringify({ kind: 'reply', inquiry_id: inquiryId, body: body })
    });
    const out = await res.json().catch(() => null);
    if(!out || !out.ok) console.warn('buyer not notified:', out && out.error);
    return !!(out && out.ok);
  }catch(err){ console.warn('buyer notification failed', err); return false; }
}

/* Tells a supplier their listing was approved or denied. Staff only — checked
   server-side against the staff table, not asked politely here. */
async function notifyDecision(applicationId, reason){
  try{
    const { data: s } = await sb.auth.getSession();
    const jwt = s && s.session && s.session.access_token;
    if(!jwt) return false;
    const res = await fetch(SUPABASE_URL + '/functions/v1/notify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY, Authorization: 'Bearer ' + jwt },
      body: JSON.stringify({ kind: 'decision', application_id: applicationId, reason: reason || '' })
    });
    const out = await res.json().catch(() => null);
    if(!out || !out.ok) console.warn('decision not sent:', out && out.error);
    return !!(out && out.ok);
  }catch(err){ console.warn('decision email failed', err); return false; }
}

/* ---- analytics ----
   visitor id is a random string kept in localStorage so repeat page loads by
   the same browser collapse into one unique hit at query time.

   Only set once the visitor has accepted analytics — see analytics.js, which
   owns the cx_consent key. Decline and we still record the view so the company
   sees its traffic; the row just carries no identifier, so it cannot be tied
   to anything or anyone. */
function visitorId(){
  try{
    if(localStorage.getItem('cx_consent') !== 'yes'){
      localStorage.removeItem('cx_v');      // clean up if they change their mind
      return null;
    }
    let v = localStorage.getItem('cx_v');
    if(!v){ v = Math.random().toString(36).slice(2) + Date.now().toString(36); localStorage.setItem('cx_v', v); }
    return v;
  }catch(e){ return null; }
}
function trackEvent(slug, kind, keyword){
  if(!sb || !slug) return;
  // fire and forget: analytics must never block or break the page
  sb.from('profile_events').insert({
    company_slug: slug, kind, keyword: keyword || null, visitor: visitorId()
  }).then(null, e => console.warn('trackEvent', e));
}

/* ---- owner reads/writes (RLS decides what is visible) ---- */
async function myCompanies(){
  if(!sb) return [];
  const { data, error } = await sb.rpc('my_companies');
  if(error){ console.error('myCompanies', error); return []; }
  return data || [];
}
/* A row-level-security refusal is NOT an error in PostgREST — a blocked update
   returns success with zero rows touched. Selecting the row back is the only
   way to tell "saved" from "silently discarded". */
async function updateCompany(slug, fields){
  if(!sb) return 'No connection';
  const { data, error } = await sb.from('companies').update(fields).eq('slug', slug).select('slug');
  if(error){ console.error('updateCompany', error); return error.message; }
  if(!data || !data.length) return 'nothing was saved — this account does not have permission to edit this company.';
  return null;
}
async function fetchMyListings(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:true });
  if(error){ console.error('fetchMyListings', error); return []; }
  return data || [];
}
async function fetchMyReviews(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('reviews').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:false });
  if(error){ console.error('fetchMyReviews', error); return []; }
  return data || [];
}
async function replyToReview(id, reply){
  if(!sb) return;
  const { error } = await sb.from('reviews').update({ reply }).eq('id', id);
  if(error) console.error('replyToReview', error);
}
async function fetchInquiries(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('inquiries').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:false });
  if(error){ console.error('fetchInquiries', error); return []; }
  return data || [];
}
async function setInquiryStatus(id, status){
  if(!sb) return;
  const { error } = await sb.from('inquiries').update({ status }).eq('id', id);
  if(error) console.error('setInquiryStatus', error);
}
async function fetchThread(inquiryId){
  if(!sb) return [];
  const { data, error } = await sb.from('inquiry_messages').select('*')
    .eq('inquiry_id', inquiryId).order('created_at');
  if(error){ console.error('fetchThread', error); return []; }
  return data || [];
}
async function postMessage(inquiryId, body){
  if(!sb) return 'No connection';
  const { error } = await sb.from('inquiry_messages').insert({ inquiry_id: inquiryId, body, author: 'supplier' });
  if(error){ console.error('postMessage', error); return error.message; }
  return null;
}
/* Views over a window, bucketed to suit it. Returns [{bucket, hits}]. */
async function companyViews(slug, fromIso, toIso, bucket){
  if(!sb || !slug) return [];
  const { data, error } = await sb.rpc('company_views',
    { p_slug: slug, p_from: fromIso, p_to: toIso, p_bucket: bucket || 'day' });
  if(error){ console.error('companyViews', error); return []; }
  return data || [];
}
async function companyStats(slug, days){
  if(!sb) return [];
  const { data, error } = await sb.rpc('company_stats', { p_slug: slug, p_days: days || 30 });
  if(error){ console.error('companyStats', error); return []; }
  return data || [];
}

/* ---- claiming ---- */
/* No account required: accounts are only created through Get Listed, so a
   claim is a request that staff verify and fulfil in the admin console. */
async function submitClaim(slug, c){
  if(!sb) return 'No connection';
  const user = await currentUser();
  const { error } = await sb.from('claims').insert({
    company_slug: slug, user_id: user ? user.id : null,
    email: c.email || (user && user.email) || '',
    name: c.name || null, role_title: c.role_title || null,
    evidence: c.evidence || null, status: 'Pending'
  });
  if(error){ console.error('submitClaim', error); return error.message; }
  return null;
}
async function fetchClaims(){
  if(!sb) return [];
  const { data, error } = await sb.from('claims').select('*').order('created_at', { ascending:false });
  if(error){ console.error('fetchClaims', error); return []; }
  return data || [];
}
/* Whoever gets a claim approved receives that listing's quote requests, so the
   question staff are really answering is "is this person actually from this
   company". Until now they had only the claimant's own typed justification.
   This compares the email domain against the company's website and its listed
   contact address — in the database, so a claimant cannot influence the answer.
   It never decides anything: it hands staff the one cheap fact worth knowing. */
async function claimEvidence(slug, email){
  if(!sb) return null;
  const { data, error } = await sb.rpc('claim_evidence', { p_slug: slug, p_email: email || '' });
  if(error){ console.error('claim_evidence', error); return null; }
  return (data && data[0]) || null;
}
/* Staff approval of a claim is what actually grants access. The claimant has no
   account when they ask, so approval attaches the login by email — create it in
   Supabase Auth first if it does not exist yet. */
async function decideClaim(claim, approve){
  if(!sb) return;
  if(approve){
    const { data, error } = await sb.rpc('attach_company_user',
      { p_slug: claim.company_slug, p_email: claim.email });
    if(error){ console.error('decideClaim attach', error); return error.message; }
    if(data === 'no-account'){
      /* No login yet — the notify function invites one (Supabase Auth sends
         that email itself, so this works before Resend is configured) and
         attaches the company to it. Staff-checked server-side. */
      const out = await inviteClaimant(claim.id);
      if(!out.ok){
        return 'No login exists for ' + claim.email + ' and the automatic invitation failed'
          + (out.error ? ' (' + out.error + ')' : '') + '. Create that user in Supabase Auth, then approve again.';
      }
    }
  }
  const { error } = await sb.from('claims').update({ status: approve ? 'Approved' : 'Denied' }).eq('id', claim.id);
  if(error){ console.error('decideClaim', error); return error.message; }
  return null;
}

/* ---- staff moderation ---- */
async function fetchAllReviews(){
  if(!sb) return [];
  const { data, error } = await sb.from('reviews').select('*').order('created_at', { ascending:false });
  if(error){ console.error('fetchAllReviews', error); return []; }
  return data || [];
}
async function setReviewStatus(id, status){
  if(!sb) return;
  const { error } = await sb.from('reviews').update({ status }).eq('id', id);
  if(error) console.error('setReviewStatus', error);
}

/* Current window, the window before it, and the view->contact->quote funnel,
   in one round trip. Returns null on failure rather than zeros, so the portal
   can say "unavailable" instead of quietly reporting a bad month. */
async function companyInsights(slug, days){
  if(!sb || !slug) return null;
  const { data, error } = await sb.rpc('company_insights', { p_slug: slug, p_days: days || 30 });
  if(error){ console.error('company_insights', error); return null; }
  return (data && data[0]) || null;
}

/* Emails the supplier that a quote request has arrived.
   The recipient is decided server-side from the company slug — this call
   cannot name an address, or the site would be an open spam relay.
   Never throws: the request is already saved in the database and visible in
   the supplier's portal, so a failed notification must not fail the form. */
async function notifySupplier(slug, quote, token){
  try{
    const res = await fetch(SUPABASE_URL + '/functions/v1/notify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY },
      /* the token lets the confirmation email link the buyer back to the
         thread; without it they get a copy of their request and no way back */
      body: JSON.stringify({ kind: 'quote', company_slug: slug, quote: quote, token: token || '' })
    });
    const out = await res.json().catch(() => null);
    if(!out || !out.ok) console.warn('supplier not notified:', out && out.error);
    return !!(out && out.ok);
  }catch(err){ console.warn('supplier notification failed', err); return false; }
}

/* Every company, including suspended ones — staff only, enforced by the
   companies_read policy rather than by asking nicely here. */
async function fetchAllCompanies(){
  if(!sb) return [];
  const { data, error } = await sb.from('companies')
    .select('slug, name, handle, email, published, suspended_at, created_at, talent_access_until')
    .order('name');
  if(error){ console.error('fetchAllCompanies', error); return []; }
  return data || [];
}

/* Staff reads for the demand data. Both are refused by the database for
   anybody who is not staff, so this is convenience, not the control. */
async function fetchTopSearches(days, missedOnly){
  if(!sb) return [];
  const { data, error } = await sb.rpc('top_searches',
    { p_days: days || 30, p_missed_only: !!missedOnly });
  if(error){ console.error('top_searches', error); return []; }
  return data || [];
}
async function fetchWanted(){
  if(!sb) return [];
  const { data, error } = await sb.from('wanted').select('*')
    .order('at', { ascending:false }).limit(200);
  if(error){ console.error('fetchWanted', error); return []; }
  return data || [];
}
async function setWantedHandled(id, handled){
  if(!sb) return 'Not connected.';
  const { error } = await sb.from('wanted').update({ handled: !!handled }).eq('id', id);
  if(error){ console.error('setWantedHandled', error); return error.message; }
  return '';
}

/* The staff audit trail. Append-only in the database, so this is a faithful
   record of what was done and by whom — including by us. */
async function fetchSecurityLog(limit){
  if(!sb) return [];
  const { data, error } = await sb.from('security_log')
    .select('*').order('at', { ascending:false }).limit(limit || 100);
  if(error){ console.error('fetchSecurityLog', error); return []; }
  return data || [];
}

/* ---- suspension ----
   Deliberately not deletion. A suspended company keeps every row it had, so a
   dispute can be reversed and a returning customer picks up where they left
   off. The database does the enforcing: a suspended listing disappears from
   the directory and from keyword results, and its owner can neither edit it
   nor lift the suspension. See set_company_suspended() in the migration. */
async function suspendCompany(slug, suspend, reason){
  if(!sb) return 'Not connected.';
  const { error } = await sb.rpc('set_company_suspended',
    { p_slug: slug, p_suspend: !!suspend, p_reason: reason || null });
  if(error){ console.error('set_company_suspended', error); return error.message; }
  return '';
}
async function suspendProfile(handle, suspend, reason){
  if(!sb) return 'Not connected.';
  const { error } = await sb.rpc('set_profile_suspended',
    { p_handle: handle, p_suspend: !!suspend, p_reason: reason || null });
  if(error){ console.error('set_profile_suspended', error); return error.message; }
  return '';
}

/* ---- logo + gallery image storage (public bucket "logos") ---- */
async function uploadImage(file){ return uploadLogo(file); }

/* Send anyone who is not a signed-in admin back to the portal. There is one
   sign-in for the whole site now; admin is a property of the account. */
async function requireStaff(){
  const user = await currentUser();
  if(!user){ location.href = 'portal'; return false; }
  const staff = await checkStaff();
  if(!staff){
    document.body.innerHTML = '<div style="max-width:520px;margin:80px auto;font-family:Arial,sans-serif;text-align:center;color:#1a1a1a">'
      + '<h2>Not authorized</h2><p style="color:#5f6368">This account isn’t on the Circuits.com staff list. '
      + 'Sign in with an account that has admin.</p><p><a href="portal" style="color:#5f9b00;font-weight:600">Back to your profile</a></p></div>';
    return false;
  }
  return true;
}

/* ===================================================================
   Added 2026-08-20: keyword index (Browse + search suggestions),
   confirmation resend, claim invitations, unanswered-request report.
   =================================================================== */

/* Every live keyword, deduped on the same normalization search uses, with how
   many companies hold it. The sample fixture never leaves the database here —
   fake companies must not appear as suggestions or on Browse. Cached for the
   page's lifetime: the list changes when staff approve something, not mid-visit. */
let KW_INDEX = null;
async function fetchKeywordIndex(){
  if(KW_INDEX) return KW_INDEX;
  if(!sb) return [];
  try{
    const { data, error } = await sb.from('applications')
      .select('keyword, keyword_norm, company_slug, company')
      .eq('status', 'Approved').eq('paused', false).limit(2000);
    if(error) throw error;
    const byNorm = new Map();
    for(const r of (data || [])){
      if(!r.keyword || !r.keyword_norm) continue;
      if(r.keyword_norm === 'sample' || /^sample-/.test(r.company_slug || '')) continue;
      const cur = byNorm.get(r.keyword_norm) || { keyword: r.keyword, norm: r.keyword_norm, companies: new Set() };
      cur.companies.add(r.company);
      byNorm.set(r.keyword_norm, cur);
    }
    KW_INDEX = [...byNorm.values()]
      .map(k => ({ keyword: k.keyword, norm: k.norm, companies: k.companies.size }))
      .sort((a, b) => a.keyword.localeCompare(b.keyword));
  }catch(err){
    console.warn('fetchKeywordIndex', err);
    return [];   // a failed load must not break search; suggestions just stay off
  }
  return KW_INDEX;
}

/* The confirmation email goes out once at sign-up; a typo or a spam filter
   used to be a dead end. Always reports success the same way — whether an
   account exists behind an address is not this button's to reveal. */
async function resendConfirmation(email){
  if(!sb) return 'No connection';
  const addr = (email || '').trim();
  if(!addr.includes('@')) return 'That does not look like an email address.';
  const { error } = await sb.auth.resend({ type: 'signup', email: addr,
    options: { emailRedirectTo: location.origin + '/portal' } });
  if(error){
    console.warn('resendConfirmation', error.message);
    const secs = (/after (\d+) seconds?/i.exec(error.message || '') || [])[1];
    if(secs) return 'An email was sent recently — you can ask for another in ' + secs + ' seconds.';
    if(error.status === 429 || /rate limit/i.test(error.message || '')){
      return 'Too many emails have gone out in the last hour. Please try again shortly.';
    }
    /* "already confirmed" arrives as an error, but it is good news */
    if(/already confirmed/i.test(error.message || '')) return 'That email is already confirmed — just sign in.';
    return 'We could not send the email just now. Please try again in a few minutes.';
  }
  return '';
}

/* Staff only, checked server-side: asks the notify function to invite the
   claimant (Supabase Auth sends the invitation, not Resend) and attach the
   company to the new login. Returns { ok, invited?, error? }. */
async function inviteClaimant(claimId){
  try{
    const { data: s } = await sb.auth.getSession();
    const jwt = s && s.session && s.session.access_token;
    if(!jwt) return { ok: false, error: 'sign in required' };
    const res = await fetch(SUPABASE_URL + '/functions/v1/notify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY, Authorization: 'Bearer ' + jwt },
      body: JSON.stringify({ kind: 'claim-invite', claim_id: claimId })
    });
    const out = await res.json().catch(() => null);
    return out || { ok: false, error: 'no response' };
  }catch(err){
    console.warn('inviteClaimant failed', err);
    return { ok: false, error: 'network' };
  }
}

/* Quote requests that have sat for days with no supplier reply — the silence
   the admin tab could not see. Staff only, enforced in the function. */
async function adminUnansweredInquiries(days){
  if(!sb) return [];
  const { data, error } = await sb.rpc('admin_unanswered_inquiries', { p_days: days || 3 });
  if(error){ console.error('admin_unanswered_inquiries', error); return []; }
  return data || [];
}
