/* ===== Circuits.com — Supabase-backed data store =====
   Real persistence shared across all clients and devices.
   Requires the Supabase JS client (loaded from CDN) before this file.
   The URL and publishable key below are PUBLIC by design (safe to embed);
   all access is enforced server-side by Row Level Security. */

const SUPABASE_URL = 'https://ghpruernzhjwsgsezdyn.supabase.co';
const SUPABASE_KEY = 'sb_publishable_zmOQinynNkuWdHUeHrFdDA_y6UnLyL4';

const sb = (window.supabase && window.supabase.createClient)
  ? window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY)
  : null;

/* ---- pricing ----
   Beta rates. Original owners keep these for as long as their subscription
   stays active, so these numbers are a floor we honour, not a list price.
   Yearly works out to ten months, i.e. two months free. */
const BASE_FEE = 99, BANNER_FEE = 399, BADGE_FEE = 49;
const BASE_FEE_YEAR = 999, BANNER_FEE_YEAR = 3999, BADGE_FEE_YEAR = 399;
function effPrice(v, fallback){
  return (v==null || v==='' || isNaN(Number(v))) ? fallback : Number(v);
}
function appPrice(a){
  let p = effPrice(a && a.listing_price, BASE_FEE);
  if(a && a.banner) p += effPrice(a.banner_price, BANNER_FEE);
  if(a && a.badge)  p += effPrice(a.badge_price, BADGE_FEE);
  return p;
}
function appPriceLabel(a){ return (a && a.fee) ? a.fee : ('$' + appPrice(a) + '/mo'); }

/* ---- read ---- */
async function fetchApplications(){
  if(!sb) return [];
  // oldest first — new listings join at the BOTTOM of the list
  // (earlier claims keep the higher permanent position)
  // secondary sort by id keeps rows from jumping when timestamps tie
  const { data, error } = await sb.from('applications').select('*')
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.error('fetchApplications', error); return []; }
  return data || [];
}
async function fetchApproved(){
  if(!sb) return [];
  const { data, error } = await sb.from('applications').select('*').eq('status','Approved')
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.error('fetchApproved', error); return []; }
  return data || [];
}
/* ===== Keyword matching ruleset =====
   1. Lowercase everything.
   2. Strip every non-letter/digit (hyphens, spaces, punctuation) — "semi-conductors" == "semi conductors" == "semiconductors".
   3. Singularize the plural tail — "sensors" == "sensor", "switches" == "switch", "batteries" == "battery".
   4. EXACT match only after normalization. No substring/partial matching, so
      "list test 2" never matches "list test 3" and "zzz" only matches "zzz".
   5. Blank/empty keywords never match anything. */
function singularize(n){
  if(n.length>4 && n.endsWith('ies')) return n.slice(0,-3)+'y';   // batteries -> battery
  if(n.length>3 && /(?:x|z|ch|sh)es$/.test(n)) return n.slice(0,-2); // switches -> switch, boxes -> box
  if(n.length>3 && n.endsWith('s') && !n.endsWith('ss')) return n.slice(0,-1); // sensors -> sensor, fuses -> fuse
  return n;
}
function normKw(s){
  return singularize((s||'').toLowerCase().replace(/[^a-z0-9]/g,''));
}
/* Approval-level cleanup for stored keywords: lowercase, no hyphens, no plurals. */
function cleanKw(s){
  let v = (s||'').toLowerCase().replace(/-+/g,' ').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();
  return v.replace(/([a-z0-9]+)$/, w => singularize(w));
}
/* One live listing per company for a searched keyword (skips paused ones).
   Postgres does the matching on an index over applications.keyword_norm, which
   is generated by norm_kw() — the SQL twin of normKw() above. This used to pull
   every approved listing into the browser and filter here, so search got slower
   with every listing sold. Still oldest-first: earlier claims keep the higher
   permanent position. */
async function fetchApprovedByKeyword(keyword){
  if(!sb) return [];
  const k = normKw(keyword);
  if(!k) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('status','Approved').eq('paused', false).eq('keyword_norm', k)
    .order('created_at', { ascending:true }).order('id', { ascending:true });
  if(error){ console.error('fetchApprovedByKeyword', error); return []; }
  const seen = new Set(), out = [];
  for(const a of (data || [])){ if(seen.has(a.company)) continue; seen.add(a.company); out.push(a); }
  return out;
}

/* ---- company logo storage (Supabase Storage, public bucket "logos") ---- */
async function uploadLogo(file){
  if(!sb || !file) return '';
  const ext = (file.name.split('.').pop() || 'png').toLowerCase().replace(/[^a-z0-9]/g,'');
  const path = Date.now() + '-' + Math.random().toString(36).slice(2,8) + '.' + ext;
  const { error } = await sb.storage.from('logos').upload(path, file, { contentType: file.type, cacheControl: '31536000' });
  if(error){ console.error('uploadLogo', error); return ''; }
  return sb.storage.from('logos').getPublicUrl(path).data.publicUrl;
}
function isLogoUrl(s){ return /^https?:\/\//i.test(s||''); }

/* ---- listing documentation storage (Supabase Storage, public bucket "docs") ---- */
async function uploadDoc(file){
  if(!sb || !file) return null;
  const ext = (file.name.split('.').pop() || 'pdf').toLowerCase().replace(/[^a-z0-9]/g,'');
  const path = Date.now() + '-' + Math.random().toString(36).slice(2,8) + '.' + ext;
  const { error } = await sb.storage.from('docs').upload(path, file, { contentType: file.type, cacheControl: '31536000' });
  if(error){ console.error('uploadDoc', error); return null; }
  return { name: file.name, url: sb.storage.from('docs').getPublicUrl(path).data.publicUrl };
}

/* ---- write ---- */
/* Join form: one submission becomes one row per keyword. */
async function addApplicationKeywords(base, keywords){
  if(!sb) throw new Error('No connection');
  const list = (keywords && keywords.length) ? keywords.map(cleanKw) : [''];
  const rows = list.map(kw => Object.assign({}, base, {
    keyword: kw, keywords: kw ? [kw] : [], status: base.status || 'Pending'
  }));
  const { error } = await sb.from('applications').insert(rows);
  if(error){ console.error('addApplicationKeywords', error); throw error; }
  return rows;
}
async function updateAppStatus(id, status){
  if(!sb) return null;
  const { error } = await sb.from('applications').update({ status }).eq('id', id);
  if(error) console.error('updateAppStatus', error);
  return error || null;
}
/* Approve every keyword row for a company (Add Listing dropdown). */
async function approveCompany(company){
  if(!sb) return;
  const { error } = await sb.from('applications').update({ status:'Approved', paused:false }).eq('company', company);
  if(error) console.error('approveCompany', error);
}
async function setPaused(id, paused){
  if(!sb) return null;
  const { error } = await sb.from('applications').update({ paused }).eq('id', id);
  if(error) console.error('setPaused', error);
  return error || null;
}
async function updateApplication(id, fields){
  if(!sb) return null;
  if('keyword' in fields){ fields.keyword = cleanKw(fields.keyword); fields.keywords = fields.keyword ? [fields.keyword] : []; }
  const { error } = await sb.from('applications').update(fields).eq('id', id);
  if(error) console.error('updateApplication', error);
  return error || null;
}
async function deleteApplication(id){
  if(!sb) return;
  const { error } = await sb.from('applications').delete().eq('id', id);
  if(error) console.error('deleteApplication', error);
}

/* ---- auth (staff) ---- */
async function currentUser(){ if(!sb) return null; const { data } = await sb.auth.getUser(); return data ? data.user : null; }
async function checkStaff(){ if(!sb) return false; const { data, error } = await sb.rpc('is_staff'); if(error){ console.error('is_staff', error); return false; } return !!data; }
/* Sign in with an email OR a Circuits.com username. Supabase only knows
   emails, so a username is resolved first. A failed lookup still calls
   signInWithPassword so a wrong username and a wrong password come back
   with the same error, rather than confirming which usernames exist. */
async function signIn(identifier, password){
  let email = (identifier || '').trim();
  if(email && !email.includes('@')){
    try{
      const { data } = await sb.rpc('email_for_login', { p_id: email });
      if(data) email = data;
    }catch(e){ console.warn('username lookup failed', e); }
  }
  return sb.auth.signInWithPassword({ email, password });
}
async function signUp(email, password){ return sb.auth.signUp({ email, password }); }
async function signOut(){ if(sb) await sb.auth.signOut(); } async function loadPrefs(page){ if(!sb) return null; const { data, error } = await sb.from('admin_prefs').select('prefs').eq('page', page).maybeSingle(); if(error){ console.error('loadPrefs', error); return null; } return data ? data.prefs : null; } async function savePrefs(page, prefs){ if(!sb) return; const { data } = await sb.auth.getUser(); if(!data || !data.user) return; const { error } = await sb.from('admin_prefs').upsert({ user_id: data.user.id, page, prefs, updated_at: new Date().toISOString() }, { onConflict: 'page' }); if(error) console.error('savePrefs', error); }

/* ===================================================================
   Company profiles
   =================================================================== */

/* Must stay identical to the SQL slugify() in the database. */
function slugify(s){
  return (s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
}
/* A company's public address is its handle, straight off the root:
   circuits.com/zzzelec — short enough to put on an advert. */
function profileUrl(handle){
  return handle ? '/' + handle : '';
}
/* Must match handle_ok() in the database. */
function handleFormatOk(h){
  return /^[a-z0-9]([a-z0-9_-]*[a-z0-9])?$/.test(h||'')
      && h.length >= 3 && h.length <= 32
      && !/--|__|_-|-_/.test(h);
}
/* Is this handle free? Returns '' if available, or the reason it is not.
   circuits.com/<name> is one namespace shared by listings and profiles, so the
   database answers this — the same function the insert triggers use. */
const HANDLE_WHY = {
  format:   '3–32 characters: letters, numbers, and single hyphens or underscores between them.',
  reserved: 'That name is reserved by Circuits.com.',
  company:  'Taken by a company listing.',
  profile:  'Taken by another profile.'
};
async function handleAvailable(handle, ownSlug, ownUser){
  const h = (handle||'').toLowerCase().trim();
  if(!handleFormatOk(h)) return HANDLE_WHY.format;
  if(!sb) return 'No connection';
  const { data, error } = await sb.rpc('handle_taken',
    { p_handle: h, p_user: ownUser || null, p_slug: ownSlug || null });
  if(error){ console.error('handle_taken', error); return 'Could not check that name right now.'; }
  return HANDLE_WHY[data] || '';
}

/* ---- profiles: a person, separate from any company listing ---- */
async function fetchProfileByHandle(handle){
  if(!sb || !handle) return null;
  const { data, error } = await sb.from('profiles').select('*')
    .ilike('handle', (handle||'').trim()).maybeSingle();
  if(error){ console.error('fetchProfileByHandle', error); return null; }
  return data;
}
async function myProfile(){
  if(!sb) return null;
  const { data, error } = await sb.rpc('my_profile');
  if(error){ console.error('my_profile', error); return null; }
  return (data && data[0]) || null;
}
async function updateMyProfile(fields){
  if(!sb) return 'No connection';
  const u = await currentUser();
  if(!u) return 'Not signed in';
  const { data, error } = await sb.from('profiles').update(fields).eq('user_id', u.id).select();
  if(error) return error.message;
  if(!data || !data.length) return 'That change was refused.';
  return '';
}
/* Register: the account and the circuits.com address are created together.
   The handle rides along as signup metadata because email confirmation means
   there is no session yet — a trigger turns it into the profile row, so the
   address is held from the moment the account exists. */
async function registerProfile(email, password, handle, displayName){
  if(!sb) return 'No connection';
  const { error } = await sb.auth.signUp({
    email, password,
    options: { data: { handle: (handle||'').toLowerCase().trim(), display_name: displayName || '' } }
  });
  return error ? error.message : '';
}

/* ---- public reads ---- */
async function fetchCompany(slug){
  if(!sb || !slug) return null;
  const { data, error } = await sb.from('companies').select('*').eq('slug', slug).maybeSingle();
  if(error){ console.error('fetchCompany', error); return null; }
  return data;
}
/* Public pages address a company by its handle, not its internal slug. */
async function fetchCompanyByHandle(handle){
  if(!sb || !handle) return null;
  const { data, error } = await sb.from('companies')
    .select('*').eq('handle', (handle||'').toLowerCase()).maybeSingle();
  if(error){ console.error('fetchCompanyByHandle', error); return null; }
  return data;
}
/* Live keywords for a company, in the permanent order they were claimed. */
async function fetchCompanyKeywords(slug){
  if(!sb || !slug) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('company_slug', slug).eq('status','Approved')
    .order('created_at', { ascending:true });
  if(error){ console.error('fetchCompanyKeywords', error); return []; }
  return (data||[]).filter(r => !r.paused && r.keyword);
}
async function fetchReviews(slug){
  if(!sb || !slug) return [];
  const { data, error } = await sb.from('reviews').select('*')
    .eq('company_slug', slug).eq('status','Approved')
    .order('created_at', { ascending:false });
  if(error){ console.error('fetchReviews', error); return []; }
  return data || [];
}
/* ---- public writes ---- */
async function submitReview(slug, r){
  if(!sb) throw new Error('No connection');
  const { error } = await sb.from('reviews').insert({
    company_slug: slug, author_name: r.name, author_email: r.email,
    rating: r.rating, body: r.body, status: 'Pending'
  });
  if(error){ console.error('submitReview', error); throw error; }
}
async function submitInquiry(slug, q){
  if(!sb) throw new Error('No connection');
  const { data, error } = await sb.from('inquiries').insert({
    company_slug: slug, from_name: q.name, from_email: q.email,
    from_company: q.company || null, phone: q.phone || null,
    subject: q.subject || null, body: q.body,
    quantity: q.quantity || null, part_number: q.part_number || null,
    status: 'New'
  }).select('id').maybeSingle();
  if(error){ console.error('submitInquiry', error); throw error; }
  return data;
}

/* ---- analytics ----
   visitor id is a random string kept in localStorage so repeat page loads by
   the same browser collapse into one unique hit at query time. */
function visitorId(){
  try{
    let v = localStorage.getItem('cx_v');
    if(!v){ v = Math.random().toString(36).slice(2) + Date.now().toString(36); localStorage.setItem('cx_v', v); }
    return v;
  }catch(e){ return null; }
}
function trackEvent(slug, kind, keyword){
  if(!sb || !slug) return;
  // fire and forget: analytics must never block or break the page
  sb.from('profile_events').insert({
    company_slug: slug, kind, keyword: keyword || null, visitor: visitorId()
  }).then(null, e => console.warn('trackEvent', e));
}

/* ---- owner reads/writes (RLS decides what is visible) ---- */
async function myCompanies(){
  if(!sb) return [];
  const { data, error } = await sb.rpc('my_companies');
  if(error){ console.error('myCompanies', error); return []; }
  return data || [];
}
/* A row-level-security refusal is NOT an error in PostgREST — a blocked update
   returns success with zero rows touched. Selecting the row back is the only
   way to tell "saved" from "silently discarded". */
async function updateCompany(slug, fields){
  if(!sb) return 'No connection';
  const { data, error } = await sb.from('companies').update(fields).eq('slug', slug).select('slug');
  if(error){ console.error('updateCompany', error); return error.message; }
  if(!data || !data.length) return 'nothing was saved — this account does not have permission to edit this company.';
  return null;
}
async function fetchMyListings(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('applications').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:true });
  if(error){ console.error('fetchMyListings', error); return []; }
  return data || [];
}
async function fetchMyReviews(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('reviews').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:false });
  if(error){ console.error('fetchMyReviews', error); return []; }
  return data || [];
}
async function replyToReview(id, reply){
  if(!sb) return;
  const { error } = await sb.from('reviews').update({ reply }).eq('id', id);
  if(error) console.error('replyToReview', error);
}
async function fetchInquiries(slug){
  if(!sb) return [];
  const { data, error } = await sb.from('inquiries').select('*')
    .eq('company_slug', slug).order('created_at', { ascending:false });
  if(error){ console.error('fetchInquiries', error); return []; }
  return data || [];
}
async function setInquiryStatus(id, status){
  if(!sb) return;
  const { error } = await sb.from('inquiries').update({ status }).eq('id', id);
  if(error) console.error('setInquiryStatus', error);
}
async function fetchThread(inquiryId){
  if(!sb) return [];
  const { data, error } = await sb.from('inquiry_messages').select('*')
    .eq('inquiry_id', inquiryId).order('created_at');
  if(error){ console.error('fetchThread', error); return []; }
  return data || [];
}
async function postMessage(inquiryId, body){
  if(!sb) return 'No connection';
  const { error } = await sb.from('inquiry_messages').insert({ inquiry_id: inquiryId, body, author: 'supplier' });
  if(error){ console.error('postMessage', error); return error.message; }
  return null;
}
/* Views over a window, bucketed to suit it. Returns [{bucket, hits}]. */
async function companyViews(slug, fromIso, toIso, bucket){
  if(!sb || !slug) return [];
  const { data, error } = await sb.rpc('company_views',
    { p_slug: slug, p_from: fromIso, p_to: toIso, p_bucket: bucket || 'day' });
  if(error){ console.error('companyViews', error); return []; }
  return data || [];
}
async function companyStats(slug, days){
  if(!sb) return [];
  const { data, error } = await sb.rpc('company_stats', { p_slug: slug, p_days: days || 30 });
  if(error){ console.error('companyStats', error); return []; }
  return data || [];
}

/* ---- claiming ---- */
/* No account required: accounts are only created through Get Listed, so a
   claim is a request that staff verify and fulfil in the admin console. */
async function submitClaim(slug, c){
  if(!sb) return 'No connection';
  const user = await currentUser();
  const { error } = await sb.from('claims').insert({
    company_slug: slug, user_id: user ? user.id : null,
    email: c.email || (user && user.email) || '',
    name: c.name || null, role_title: c.role_title || null,
    evidence: c.evidence || null, status: 'Pending'
  });
  if(error){ console.error('submitClaim', error); return error.message; }
  return null;
}
async function fetchClaims(){
  if(!sb) return [];
  const { data, error } = await sb.from('claims').select('*').order('created_at', { ascending:false });
  if(error){ console.error('fetchClaims', error); return []; }
  return data || [];
}
/* Staff approval of a claim is what actually grants access. The claimant has no
   account when they ask, so approval attaches the login by email — create it in
   Supabase Auth first if it does not exist yet. */
async function decideClaim(claim, approve){
  if(!sb) return;
  if(approve){
    const { data, error } = await sb.rpc('attach_company_user',
      { p_slug: claim.company_slug, p_email: claim.email });
    if(error){ console.error('decideClaim attach', error); return error.message; }
    if(data === 'no-account'){
      return 'No login exists for ' + claim.email + ' yet. Create that user in Supabase Auth, then approve again.';
    }
  }
  const { error } = await sb.from('claims').update({ status: approve ? 'Approved' : 'Denied' }).eq('id', claim.id);
  if(error){ console.error('decideClaim', error); return error.message; }
  return null;
}

/* ---- staff moderation ---- */
async function fetchAllReviews(){
  if(!sb) return [];
  const { data, error } = await sb.from('reviews').select('*').order('created_at', { ascending:false });
  if(error){ console.error('fetchAllReviews', error); return []; }
  return data || [];
}
async function setReviewStatus(id, status){
  if(!sb) return;
  const { error } = await sb.from('reviews').update({ status }).eq('id', id);
  if(error) console.error('setReviewStatus', error);
}

/* ---- logo + gallery image storage (public bucket "logos") ---- */
async function uploadImage(file){ return uploadLogo(file); }

/* Redirect to login unless the visitor is a signed-in staff member. */
async function requireStaff(){
  const user = await currentUser();
  if(!user){ location.href = 'login'; return false; }
  const staff = await checkStaff();
  if(!staff){
    document.body.innerHTML = '<div style="max-width:520px;margin:80px auto;font-family:Arial,sans-serif;text-align:center;color:#1a1a1a">'
      + '<h2>Not authorized</h2><p style="color:#5f6368">This account isn’t on the Circuits.com staff list. '
      + 'Sign in with an approved staff email.</p><p><a href="login" style="color:#5f9b00;font-weight:600">Back to sign in</a></p></div>';
    return false;
  }
  return true;
}
